server:
  port: 8100

spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
#            allowedOrigins: "http://localhost:8080"
            allowedMethods:
              - Get
              - Post
            allowedHeaders: "*"
      routes:
        - id: core-products
          uri: "http://localhost:8050"
          predicates:
            - Path=/core/products/**
          filters:
            - StripPrefix=2
            - PrefixPath=/products
            - JwtAuthFilter
        - id: core-order
          uri: "http://localhost:8050"
          predicates:
            - Path=/core/orders/**
          filters:
            - StripPrefix=2
            - PrefixPath=/orders
            - JwtAuthFilter
        - id: cart-service
          uri: "http://localhost:8150"
          predicates:
            - Path=/cart/**
          filters:
            - StripPrefix=1
            - PrefixPath=/cart
            - JwtAuthFilter
        - id: auth-service
          uri: "http://localhost:8250"
          predicates:
            - Path=/auth
          filters:
            - StripPrefix=1
            - PrefixPath=/auth
#            - JwtAuthFilter


jwt:
  secret: ADAskddslfadsflkjFFJSDffjasdlfjlFSDKFjhfaksjdfhKJDFHSLKDfjhlf