server:
  port: 8000

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:8080"
#            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
            allowedHeaders: "*"
      routes:
        - id: core-service
          uri: http://localhost:8100
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=1
            - PrefixPath=/api/v1/advertisement
            - JwtAuthFilter
        - id: auth-service
          uri: http://localhost:8200
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - PrefixPath=/api/v1/auth
            - JwtAuthFilter

jwt:
  secret: h4f8093h4f983yhrt9834hr0934hf0hf493g493gf438rh438th34g34g
