server:
  port: 8250
spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_example
      username: root
      password: admin

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

    hibernate:
      ddl-auto: update